linters:
  rubocop:
    display_cop_names: true
  eslint:
    # indicate where is the config file for stylelint
    config: "./.eslintrc.json"
files:
  ignore:
    - "bin/*"
    - "db/*"
    - "config/*"
    - "Guardfile"
    - "Rakefile"
    - "node_modules/**/**"
