linters:
  eslint:
    config: "./.eslintrc.json"
  rubocop:
    display_cop_names: true

files:
  ignore:
    - "bin/*"
    - "db/*"
    - "config/*"
    - "Guardfile"
    - "Rakefile"
    - "node_modules/**/**"
